---
development:
  cloud_name: diffux
  api_key: '888156619842752'
  api_secret: b4kHMUkMtDUuBet8A1RxymeoOdQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: diffux
  api_key: '888156619842752'
  api_secret: b4kHMUkMtDUuBet8A1RxymeoOdQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: diffux
  api_key: '888156619842752'
  api_secret: b4kHMUkMtDUuBet8A1RxymeoOdQ
  enhance_image_tag: true
  static_image_support: false
