development:
  adapter: postgresql
  encoding: unicode
  database: diffux_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: diffux_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: diffux_production
  pool: 5
  username: diffux
  password:
